spring.application.name=academic-management-api
#server port
server.port=8080

#Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/academic_management
spring.datasource.username=academic_user
spring.datasource.password=academic_password
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT configuration
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=3600000
